spring:
  application:
    name: EquipmentManagementAPI
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/equipment_management}
    username: ${DBMS_USER:root}
    password: ${DBMS_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

cors:
  allowed:
    origins: ${CORS_URL:http://localhost:3000}